### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by ivnc**
#### Changes made

* Corrected relative imports to be Python 3 compatible.
* Changed last tested NVDA version to "2019.3.0".

#### Testing performed

1. With NVDA 2019.2RC2: no issues were detected.
2. With NVDA alpha 18330,b4db7dca: no issues were detected.

Testing environment
* Windows 10 version 1803 (build 17134.885).
* Focus 40 Blue 5th Generation braille display, table lambda-esp.utb.
* LAMBDA version 1.44.

Addon package to test (change .zip by .nvda-addon, uploading addon packages is not allowed by GitHub): [lambda-1.2.3-dev.zip](https://github.com/lambda-nvda/lambdaNvda/files/3482565/lambda-1.2.3-dev.zip)

Please test and comment with your results.

### CODE REVIEW

**Comment by ivnc** [comment]
Possible compatibility issue in lambdaEdit, line 33: if EditableTextDisplayModelTextInfo._storyFieldsAndRects[1] contains something different from floats, it may be required to ensure that the value of LambdaEditorFlatTextInfo.rects is int, as Python 3 as changed the effects of / operator.
CC @albzan

**Comment by albzan** [comment]
Hello Iván,

Maybe there is also something with if statements that I have to check.
I'll see in the next weeks and I'll help on compatibility with Py3.

Cheers,

Alberto

Il giorno ven 9 ago 2019 alle ore 19:50 Iván Novegil <
notifications@github.com> ha scritto:

**Comment by ivnc** [comment]
Is this PR ready to merge? The transition to Python 3 in NVDA is at the final phase...

Regards.

**Review by nvdaes — COMMENTED** [review]
Imo, changes about imports are right. However, due to modifications in displayModel, this should be reviewed by @albzan in case more changes are required.

**Comment by albzan** [comment]
Hi All,
Thank you @ivnc for your help. Yes, I have to look into this and I'll check for this.
For the "stable" tag, we can delete it, we should keep the "latest" tag
I use the "latest" to have a unique url that redirect to the latest version. This url has been shared before the addon was in the official Add-Ons pages, and so a few sites have this, like here:
http://vediamoinsieme.altervista.org/lambda-con-nvda-addon/

Alberto

**Comment by ivnc** [comment]
According to my tests the migrated version seems to be OK. Is it strictly necessary to break compatibility with Py2?

Regards.

**Comment by albzan** [comment]
Theoretically no, can you do a test with 2.x?
I'm in train right now and I can't do.
Thanks
Alberto

Il giorno gio 13 feb 2020 alle ore 13:49 Iván Novegil <
notifications@github.com> ha scritto:

**Comment by ivnc** [comment]
In my comment I was making reference to the code, but in fact the latest code seems to be compatible with NVDA 2019.2.1 as well. Pleas test by your own to confirm this.
As it looks like no more code changes are needed, let's merge.

Regards.

**Pull request merged**
