### PR TITLE
Make the last character unselected can be reported

### PR DESCRIPTION
**Pull request by nvdaes**
For testing carefully before merging

### CODE REVIEW

**Comment by albzan** [comment]
Yeah, That's a way but it reports unselected also for long text:
1. write an expression
2. go to the beginning of the line
3. press ctrl+end
4. press left arrow (for instance you have copied it)

... you will listen this long peice of text repeated wit the "unselected" announcement.
That's why I set that control.
What do you think?
Alberto

**Comment by nvdaes** [comment]
Really I don't know. I follow your exact steps and nothing is
repeated. For me it works fine.

2017-05-17 19:55 GMT+02:00, albzan <notifications@github.com>:

**Comment by albzan** [comment]
Yeah sorry,
I was wrong with steps:

1. write an expression like 20-{5*10-[(4*12-3)/9+12(15/5+1)]}/7
2. go to the beginning of the line (home)
3. press shift+end to select the line (i.e. you want to copy it
4. press left arrow

... you will listen this long peice of text repeated wit the "unselected" announcement.
You are unable to understand what's the character under the cursor
That's why I set that control.
What do you think?
Alberto

**Comment by nvdaes** [comment]
A, I understand now. I think it's better that extra info is spoken,
but no wrong or missing things. Just an opinion.

2017-05-17 20:49 GMT+02:00, albzan <notifications@github.com>:

**Comment by nvdaes** [comment]
Another option, if possible, would be to make a jack in the move caret
scripts, so that if just arrows are pressed and text is selected,
change selection is not spoken.

2017-05-17 20:49 GMT+02:00, albzan <notifications@github.com>:

**Comment by albzan** [comment]
Eh, That's definetly a matter of taste. Personally I find it boring when working with a braille display...
Because when you select some text and then you press a CR, you listen the speech that start and you have to stop it with Control...
I don't know...

**Comment by nvdaes** [comment]
Yes, this is true. Maybe a setting to choose this behavior?

2017-05-17 21:00 GMT+02:00, albzan <notifications@github.com>:

**Comment by albzan** [comment]
Yes we can set it up easilly...

**Comment by albzan** [comment]
Would you like to update the pull request? 
We can set an option: silentUnselection and add an extra condition on the If...
Thanks

**Comment by nvdaes** [comment]
Hi, updated now. Please look if it's according to your style (I tried
it) and so on.
Cheers.

2017-05-17 21:06 GMT+02:00, albzan <notifications@github.com>:

**Pull request merged**
