### PR TITLE
Spanish translation: updated interface translation, added translated documentation

### PR DESCRIPTION
**Pull request by ivnc**
-Translated new strings (addon/locale/es/LC_MESAGES/nvda.po).
-Translated documentation (addon/doc/es/readme.md).

Any problem please comment.

### CODE REVIEW

**Comment by ivnc** [comment]
Please wait until merge this pull. Tomorrow I'll make a new one commit updating readme.md.

**Comment by albzan** [comment]
Ok, thanks. If you see edits on readme, I've only added an "s" to "brailleTables" ("brailleTable" to "brailleTables") on the file path.

**Comment by ivnc** [comment]
All done, I think.

any problem comment.

Regards.

**Comment by albzan** [comment]
All right! Thank you so much!
Regards,

**Pull request merged**
